### ISSUE TITLE
Factor columns in WOE/IV calculation

### ISSUE THREAD

**Issue by navdeep-G** [klarsen1/Information#1]
Hi,

Just wondering if the WOE & IV handles factor columns differently than if they were some type of integer column/id? I have seen some different variable outcomes when using create_infotables() 
when having my character columns converted to factors versus when I convert them to numeric id's.

**Comment by klarsen1** [comment]
Yes, when you code a variable as a factor, the code treats the variable as a character and does not do any binning. Variables that are truly numeric -- i.e., "continuous" variables -- should be kept numeric.
