### ISSUE TITLE
WOE signage in calculation

### ISSUE THREAD

**Issue by kimnewzealand** [klarsen1/Information#2]
Hi there 

Thanks for your Information package.

I have been using the create_infotables and plot_infotables function but I was wondering about the sign of the WOE value. Using the German credit data, variable checkingstatus1 level A11 for example, I manually calculate the WOE as -0.818 whereas it is calculated as 0.818 in create_infotables function. As such the plot_infotables plots the positive 0.818. My calculation of the IV is the same ie 0.206.

See below my example:

# Load german credit data
url <- ("http://www.biz.uiowa.edu/faculty/jledolter/DataMining/germancredit.csv")
creditdata <- readr::read_csv(url)

# Use the CrossTable function from gmodels package on default and checkingstatus1 
gmodels::CrossTable(creditdata$Default,
                    creditdata$checkingstatus1, prop.r= TRUE, prop.c =FALSE, prop.t=FALSE, 
                    chisq = TRUE)

# Manually calculate WOE for A11
percentgood <- 0.1985714 
percentbad <- 0.45
odds <- percentgood/percentbad
woe <- log(odds)

# Create a WOE table with IV values
IV <- create_infotables(data=creditdata,
                        y="default")
plot_infotables(IV,"checkingstatus1", show_values=TRUE)

**Comment by klarsen1** [comment]
First, I'd recommend that you use the version in CRAN (if you're not already doing that).

Isn't this just an issue of what we label as goods and bads?

My package calculates WOE this way:

  sum_y_1 <- sum(t$y_1)
  sum_y_0 <- sum(t$y_0)  
  t$WOE <- ifelse(t$y_1>0 & t$y_0>0, log((t$y_1*sum_y_0)/(t$y_0*sum_y_1)), 0)  

which is simply: ln[ (y1/sum(y1)) / (y0/sum(y0)) ]

where y_1 is 1 when your dependent variable equals 1.

y_1 and y_0 are created this way:

  data$y_1 <- data[[y]]
  data$y_0 <- ifelse(data$y_1==1, 0, 1) 

Now, if we flip the labeling, then:

LN(0.45/0.1985714) = 0.86

**Comment by kimnewzealand** [comment]
Thanks for the reply. 

Yes I am using the CRAN version.

It does appear to be the issue of what is labelled as good or bad. In my case I am labeling 1 as bad, whereas your package assumes 1 as good. So if I would like to keep my labeling for modeling purposes, is there perhaps a parameter to flag which label one is using. The package would create y_1 and y_0 accordingly and plot_tables would plot WOE as calculated.

**Comment by klarsen1** [comment]
I didn't even think about goods and bads when I coded this. I just thought about 1s and 0s – the package wasn't really meant specifically for credit risk. I'd say, for now, just create another column or something when you run the package. If I have to do surgery on the package again, I will add it. But it won't be soon.
